apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-test
  namespace: jenkins
spec:
  serviceName: "nginx-test"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: nginx
          image: $IMAGE_NAME
          ports:
            - containerPort: 80
          env:
            - name: apiserver.cluster.local
              value: 192.168.40.210